### ISSUE TITLE
시작화면 바꾸기

### ISSUE THREAD

**Issue by joonjeong** [hufscse-linux/rails-blog#5]
http://localhost:3000에 접속하면 단순한 페이지만 나오는데, 이걸 다른것으로 바꾸어보자.

`config/routes.rb` 를 수정하면 되고, `rails g controller home index` 를 입력하면 간단한 페이지를 만들 수 있다.

rails guide를 참고하면서 해볼것.

**Comment by SunKyu** [comment]
넵 슬랙 테스트 해봅니다
